apiVersion: iam.scaleway.upbound.io/v1alpha1
kind: Application
metadata:
  name: iam-application
spec:
  forProvider:
    name: crossplane-iam-application
    description: an iam application
  providerConfigRef:
    name: default