apiVersion: lb.scaleway.upbound.io/v1alpha1
kind: LB
metadata:
  name: lb-instance
spec:
  forProvider:
    name: crossplane-lb-instance
    type: LB-S
    ipIdRef:
      name: lb-ip
  providerConfigRef:
    name: default
---
apiVersion: lb.scaleway.upbound.io/v1alpha1
kind: IP
metadata:
  name: lb-ip
spec:
  forProvider: {}
  providerConfigRef:
    name: default