apiVersion: function.scaleway.upbound.io/v1alpha1
kind: FunctionNamespace
metadata:
  name: function-namespace
spec:
  forProvider:
    name: crossplane-function-namespace
  providerConfigRef:
    name: default
