apiVersion: container.scaleway.upbound.io/v1alpha1
kind: Container
metadata:
  name: container
spec:
  forProvider:
    name: crossplane-container
    namespaceIdRef:
      name: container-namespace
  providerConfigRef:
    name: default
---
apiVersion: container.scaleway.upbound.io/v1alpha1
kind: ContainerNamespace
metadata:
  name: container-namespace
spec:
  forProvider:
    name: crossplane-container-namespace
  providerConfigRef:
    name: default
