apiVersion: container.scaleway.upbound.io/v1alpha1
kind: ContainerNamespace
metadata:
  name: container-namespace
spec:
  forProvider:
    name: crossplane-container-namespace
  providerConfigRef:
    name: default
