apiVersion: object.scaleway.upbound.io/v1alpha1
kind: Policy
metadata:
  annotations:
    meta.upbound.io/example-id: object/v1alpha1/policy
  labels:
    testing.upbound.io/example-name: bucket
  name: bucket
spec:
  forProvider:
    name: some-unique-name

---

