apiVersion: iot.scaleway.upbound.io/v1alpha1
kind: Device
metadata:
  name: iot-device
spec:
  forProvider:
    name: crossplane-device
    hubIdRef:
      name: iot-hub
  providerConfigRef:
    name: default
---
apiVersion: iot.scaleway.upbound.io/v1alpha1
kind: Hub
metadata:
  name: iot-hub
spec:
  forProvider:
    name: crossplane-hub
    productPlan: plan_shared
  providerConfigRef:
    name: default