apiVersion: iot.scaleway.upbound.io/v1alpha1
kind: Network
metadata:
  name: iot-network
spec:
  forProvider:
    name: crossplane-network
    type: sigfox
    hubIdRef:
      name: iot-hub
    providerConfigRef:
      name: default
---
apiVersion: iot.scaleway.upbound.io/v1alpha1
kind: Hub
metadata:
  name: iot-hub
spec:
  forProvider:
    name: crossplane-hub
    productPlan: plan_shared
  providerConfigRef:
    name: default