apiVersion: rdb.scaleway.upbound.io/v1alpha1
kind: Privilege
metadata:
  annotations:
    meta.upbound.io/example-id: rdb/v1alpha1/privilege
  labels:
    testing.upbound.io/example-name: priv
  name: priv
spec:
  forProvider:
    databaseName: my-db-name
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: rdb
    permission: all
    userName: my-db-user

---

apiVersion: rdb.scaleway.upbound.io/v1alpha1
kind: Database
metadata:
  annotations:
    meta.upbound.io/example-id: rdb/v1alpha1/privilege
  labels:
    testing.upbound.io/example-name: main
  name: main
spec:
  forProvider:
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: pgsql
    name: foobar

---

apiVersion: rdb.scaleway.upbound.io/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: rdb/v1alpha1/privilege
  labels:
    testing.upbound.io/example-name: main
  name: main
spec:
  forProvider:
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: pgsql
    isAdmin: false
    name: foobar
    passwordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system

---

