apiVersion: rdb.scaleway.upbound.io/v1alpha1
kind: DatabaseBackup
metadata:
  name: rdb-database-backup
spec:
  forProvider:
    name: crossplane-rdb-database-backup
    instanceIdRef:
      name: rdb-instance
    databaseName: crossplane-rdb-database
  providerConfigRef:
    name: default
---
apiVersion: rdb.scaleway.upbound.io/v1alpha1
kind: Database
metadata:
  name: rdb-database
spec:
  forProvider:
    name: crossplane-rdb-database
    instanceIdRef:
      name: rdb-instance
  providerConfigRef:
    name: default
---
apiVersion: v1
kind: Secret
metadata:
  name: rdb-instance-secret
  namespace: default
stringData:
  password: "thiZ_is_v&ry_s3cret"
---
apiVersion: rdb.scaleway.upbound.io/v1alpha1
kind: Instance
metadata:
  name: rdb-instance
spec:
  forProvider:
    name: crossplane-rdb-instance
    nodeType: DB-DEV-S
    engine: "PostgreSQL-14"
    isHaCluster: false
    disableBackup: true
    userName: admin
    passwordSecretRef:
      key: password
      name: rdb-instance-secret
      namespace: default
  providerConfigRef:
    name: default