apiVersion: instance.scaleway.upbound.io/v1alpha1
kind: PlacementGroup
metadata:
  name: instance-placement-group
spec:
  forProvider:
    name: crossplane-placement-group
    policyMode: enforced
    policyType: low_latency
  providerConfigRef:
    name: default