apiVersion: instance.scaleway.upbound.io/v1alpha1
kind: SecurityGroup
metadata:
  name: instance-security-group
spec:
  forProvider:
    name: crossplane-security-group
    inboundDefaultPolicy: "drop"
  providerConfigRef:
    name: default