apiVersion: instance.scaleway.upbound.io/v1alpha1
kind: SecurityGroupRule
metadata:
  name: instance-security-group-rules
spec:
  forProvider:
    securityGroupIdRef:
      name: instance-security-group
    inboundRule:
      - action: drop
        port: 443
        ipRange: "0.0.0.0/0"
---
apiVersion: instance.scaleway.upbound.io/v1alpha1
kind: SecurityGroup
metadata:
  name: instance-security-group
spec:
  forProvider:
    name: crossplane-security-group
  providerConfigRef:
    name: default